//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IniciadorEstadisticasGlobalesSoap
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/", ConfigurationName="IniciadorEstadisticasGlobalesSoap.IniciarConsultaEstadisticasGlobales")]
    public interface IniciarConsultaEstadisticasGlobales
    {
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/IniciarConsultaEstadisticasGlobales/iniciar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<IniciadorEstadisticasGlobalesSoap.iniciarResponse> iniciarAsync(IniciadorEstadisticasGlobalesSoap.iniciarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/")]
    public partial class EstadisticasGlobalesType
    {
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private int numeroTotalFacturasEmitidasField;
        
        private double sumaTotalImportesField;
        
        private int numeroTotalFacturasValidasField;
        
        private int numeroTotalFacturasSubsanadasField;
        
        private int numeroTotalFacturasAnuladasField;
        
        private int numeroTotalFacturasInvalidasField;
        
        private int numeroTotalReportesCreadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaInicio
        {
            get
            {
                return this.fechaInicioField;
            }
            set
            {
                this.fechaInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin
        {
            get
            {
                return this.fechaFinField;
            }
            set
            {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroTotalFacturasEmitidas
        {
            get
            {
                return this.numeroTotalFacturasEmitidasField;
            }
            set
            {
                this.numeroTotalFacturasEmitidasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double sumaTotalImportes
        {
            get
            {
                return this.sumaTotalImportesField;
            }
            set
            {
                this.sumaTotalImportesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroTotalFacturasValidas
        {
            get
            {
                return this.numeroTotalFacturasValidasField;
            }
            set
            {
                this.numeroTotalFacturasValidasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numeroTotalFacturasSubsanadas
        {
            get
            {
                return this.numeroTotalFacturasSubsanadasField;
            }
            set
            {
                this.numeroTotalFacturasSubsanadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int numeroTotalFacturasAnuladas
        {
            get
            {
                return this.numeroTotalFacturasAnuladasField;
            }
            set
            {
                this.numeroTotalFacturasAnuladasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int numeroTotalFacturasInvalidas
        {
            get
            {
                return this.numeroTotalFacturasInvalidasField;
            }
            set
            {
                this.numeroTotalFacturasInvalidasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int numeroTotalReportesCreados
        {
            get
            {
                return this.numeroTotalReportesCreadosField;
            }
            set
            {
                this.numeroTotalReportesCreadosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciar", WrapperNamespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/", IsWrapped=true)]
    public partial class iniciarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WSKey;
        
        public iniciarRequest()
        {
        }
        
        public iniciarRequest(string WSKey)
        {
            this.WSKey = WSKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iniciarResponse", WrapperNamespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/", IsWrapped=true)]
    public partial class iniciarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IniciadorEstadisticasGlobalesSoap.EstadisticasGlobalesType datosEntrada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/IniciarConsultaEstadisticasGlobales/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensajeSalida;
        
        public iniciarResponse()
        {
        }
        
        public iniciarResponse(IniciadorEstadisticasGlobalesSoap.EstadisticasGlobalesType datosEntrada, string mensajeSalida)
        {
            this.datosEntrada = datosEntrada;
            this.mensajeSalida = mensajeSalida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IniciarConsultaEstadisticasGlobalesChannel : IniciadorEstadisticasGlobalesSoap.IniciarConsultaEstadisticasGlobales, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class IniciarConsultaEstadisticasGlobalesClient : System.ServiceModel.ClientBase<IniciadorEstadisticasGlobalesSoap.IniciarConsultaEstadisticasGlobales>, IniciadorEstadisticasGlobalesSoap.IniciarConsultaEstadisticasGlobales
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IniciarConsultaEstadisticasGlobalesClient() : 
                base(IniciarConsultaEstadisticasGlobalesClient.GetDefaultBinding(), IniciarConsultaEstadisticasGlobalesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IniciarConsultaEstadisticasGlobalesSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IniciarConsultaEstadisticasGlobalesClient(EndpointConfiguration endpointConfiguration) : 
                base(IniciarConsultaEstadisticasGlobalesClient.GetBindingForEndpoint(endpointConfiguration), IniciarConsultaEstadisticasGlobalesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IniciarConsultaEstadisticasGlobalesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IniciarConsultaEstadisticasGlobalesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IniciarConsultaEstadisticasGlobalesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IniciarConsultaEstadisticasGlobalesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IniciarConsultaEstadisticasGlobalesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<IniciadorEstadisticasGlobalesSoap.iniciarResponse> iniciarAsync(IniciadorEstadisticasGlobalesSoap.iniciarRequest request)
        {
            return base.Channel.iniciarAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IniciarConsultaEstadisticasGlobalesSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IniciarConsultaEstadisticasGlobalesSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:14105/IniciarConsultaEstadisticasGlobales/IniciarConsultaEstadis" +
                        "ticasGlobalesSOAP");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IniciarConsultaEstadisticasGlobalesClient.GetBindingForEndpoint(EndpointConfiguration.IniciarConsultaEstadisticasGlobalesSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IniciarConsultaEstadisticasGlobalesClient.GetEndpointAddress(EndpointConfiguration.IniciarConsultaEstadisticasGlobalesSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            IniciarConsultaEstadisticasGlobalesSOAP,
        }
    }
}
